### ISSUE TITLE
Alternative to limit/offset schema for deals history

### ISSUE THREAD

**Issue by LifeMoroz** [whitebit-exchange/api-docs#10]
Hello!

I want to poll my history deals, but i creating trades frequently and schema with limit/offset is not useful due to moving orders between pages.

Can you provide possibility to specify timestamp of trade or trade id from which page starts?

**Comment by john-whitebit** [comment]
Hello!
To effectively track your trade history with frequent updates, I recommend using the deals_subscribe method available in the WebSocket API. This method allows you to subscribe to real-time updates of your trading activity, ensuring you receive immediate notifications of new trades as they occur. This approach can help you stay updated without relying on pagination through limit/offset, which might not be ideal for rapidly changing data. For more details on implementing this, you can refer to the [WhiteBIT API Documentation](https://docs.whitebit.com/private/websocket/#subscribe-4).
