### ISSUE TITLE
The same request returns either an array or a single object

### ISSUE THREAD

**Issue by alokym86** [whitebit-exchange/api-docs#100]
According to the documentation `/api/v4/orders` returns an array of the active orders. But! If provide either `orderId` or `clientOrderId` it returns just a single! object, not the object inside the array in a case such order is present and active. But if `orderId` is not found it returns an empty array. Array again, not empty result.

Returning a single object is a bug or an undocumented feature?

**Comment by john-whitebit** [comment]
Hello alokym86. Fix has been released on production!
Thank you for collaboration!
