### ISSUE TITLE
Wrong base_volume field in Recent Trades request 

### ISSUE THREAD

**Issue by alokym86** [whitebit-exchange/api-docs#101]
Request to `https://whitebit.com/api/v4/public/trades/BTC_USDT` returned an array where `quote_volume` is ALWAYS equal to `price`. E.g.: `{"tradeID":2104756232,"price":"21372.02","quote_volume":"0.014023","base_volume":"21372.02","trade_timestamp":1661524313,"type":"buy"}`
Somebody bought 21k BTC in one trade?! Are you seriosly?

**Comment by john-whitebit** [comment]
Hello, alokym86.
Thank you for submitting an issue. We will fix this bug ASAP.

**Comment by john-whitebit** [comment]
Hi again. Fix has been released on production!
Thank you for collaboration!
