### ISSUE TITLE
Subscribing to balance with nonexistent assets doesn't respond with any error.

### ISSUE THREAD

**Issue by alokym86** [whitebit-exchange/api-docs#114]
Subscribing to the random value as an asset is successful. Is it the correct behavior?
request:`{"id":1,"method":"balanceSpot_subscribe","params":["XXXXXXX","BTC_USDT","WAVES_USDT","dawadwdaw"]}`
response: `{"error": null, "result": {"status": "success"}, "id": 1}`

**Comment by john-whitebit** [comment]
Hello alokym86!
Response means that subscription request was successful. It does not show the subscription status for every asset on its own.
