### ISSUE TITLE
Cancel order api response check

### ISSUE THREAD

**Issue by emresevinc** [whitebit-exchange/api-docs#125]
Is it enough following code for cancel order api request response finished success?

if(HttpStatus == 200 && dealStock == 0 && dealMoney ==0) {
  // order is definitely cancelled
} 

Or any simple way?

**Comment by john-whitebit** [comment]
Hello, emresevinc.
On [this endpoint](https://whitebit-exchange.github.io/api-docs/docs/Private/http-trade-v4#cancel-order) response code 200 means definitely canceled order.
