### ISSUE TITLE
DBTC_DUSDT orderbook not accessible on api v4

### ISSUE THREAD

**Issue by cygnuson** [whitebit-exchange/api-docs#37]
Example route:https://whitebit.com/api/v4/public/orderbook/DBTC_DUSDT

produces {"error":"Market is not available"}

EXPECTED RESULT same as: https://whitebit.com/api/v4/public/orderbook/BTC_USDT

This market is available when using v4 recent trades.

**Comment by john-whitebit** [comment]
Hello. This endpoint is used by rating platforms such as Coingecko and CoinMarketCap. Since this is a demo market, we cannot provide them with data on non-existent currencies.

**Comment by cygnuson** [comment]
It looks like the web-socket interface will work better  for this, would you agree?

**Comment by cygnuson** [comment]
Not an issue, behavior is intended
