### ISSUE TITLE
Python - Пару вопросов, на случай если есть пара минут на них

### ISSUE THREAD

**Issue by KirillPleshakov** [whitebit-exchange/api-docs#44]
1. Возможно ли как-то програмно скачать историческую дату? Open, High, Low, Close например на BTC_USDT ? Если да - то как? 

2. Можно пожалуйста пример запроса с Public WebSocket API - https://github.com/whitebit-exchange/api-docs/blob/master/Public/websocket.md#last-price например Last price 

Спасибо огромное!

**Comment by KirillPleshakov** [comment]
Python

**Comment by eugenesaenko** [comment]
Привет!

1. Для этого можно использовать [этот эндпоинт](https://github.com/whitebit-exchange/api-docs/blob/master/Public/http-v1.md#kline) 
2. Подготовим код и обновим репозиторий.

Спасибо за обращение!

**Comment by KirillPleshakov** [comment]
2. Не хватает навыка пользования JSON - но если дать еще один пример конкретно по Last Price - то он дополнит картину полностью.

1. Спасибо! я вот сутра на свежую голову сам его нашел еще до прочтения ответа

скачать можно только за 24 часа и минутный "1m" интервал вообще не доступен ( 

Меня конкретно интересует "1h" - но за 24 часа - это как-то совсем скудно, допустим у Еторо etoro.com можно скачать за полтора месяца часовой график

Мне бы хотя бы за неделю.

Есть идеи?

Спасибо огромное!

**Comment by eugenesaenko** [comment]
2. Вот пример общения с WebSocket API. Обрати внимание, что нужно запоминать id запроса, чтобы смочь отловить ответ.

requirements.txt:
```
websocket-client
```

ws-client.py
```python
import websocket
try:
    import thread
except ImportError:
    import _thread as thread
import time
import json

my_request_id = 123;
request = {"id": my_request_id, "method": "lastprice_request", "params": ["ETH_BTC"]}

def on_message(ws, message):
    msg_json = json.loads(message)
    if (msg_json['id'] == my_request_id):
        print(message)

def on_error(ws, error):
    print(error)

def on_close(ws, close_status_code, close_msg):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        ws.send(json.dumps(request))
        time.sleep(1)
        ws.close()
        print("exiting...")

    thread.start_new_thread(run, ())


if __name__ == "__main__":
    ws = websocket.WebSocketApp("wss://api.whitebit.com/ws",
                              on_open=on_open,
                              on_message=on_message,
                              on_error=on_error,
                              on_close=on_close)

    ws.run_forever()

```

**Comment by eugenesaenko** [comment]
По поводу диапазона - в запросе можно указывать start и end время, тем самым двигаться по истории kline.

**Comment by dronov-dmitry** [comment]
Подскажите плз, а как отловить ID?
