### ISSUE TITLE
Як повинен виглядати запит, щоб сервер видав поточну ціну монети?

### ISSUE THREAD

**Issue by Nazariy003** [whitebit-exchange/api-docs#6]
Підкажіть як повинен виглядати запит щоб сервер віддав поточну ціну монети ? Наприклад пари WBT-USDT

**Comment by john-whitebit** [comment]
Доброго дня, Nazariy003.
Ви можете зробити запит на цей [ендпоінт](https://whitebit-exchange.github.io/api-docs/public/http-v1/#single-market-activity) та по ключу last взяти поточну ціну.
