### ISSUE TITLE
Feedback for “Private HTTP API V4 for trading”

### ISSUE THREAD

**Issue by ShykerBogdan** [whitebit-exchange/api-docs#8]
Доброго дня, 
маю питання щодо BulkLimitOrder
коли вказую ioc true чи є можливість передати amount який було заповнено в наступний ордер з bulk? 
можливо якщо просто вкажу 3 лімітних ордери і ціну та обєм вкажу тільки в першому?

Приклад кейсу:
1) перший лімітний ордер в bulk купує ефір на 500 доларів
2) другий автоматично бере точну кількість отриманих ефірів з першого оредру, який по факту заповнився на 200 доларів(користувач апі не вказує цю кількість сам)
3) третій бере точну кількість отирманих біткоінів з проданого ефіру

Дякую

**Comment by john-whitebit** [comment]
Доброго дня, ShykerBogdan!
Нажаль на даний час в нас немає такої можливості.
В майбутньому ми будемо розширювати функціональність торгівлі на нашій платформі, ваш запит є дуже цінним!
Дякую!
