### ISSUE TITLE
Websocket Private Authentication

### ISSUE THREAD

**Issue by 82bladerunner** [whitebit-exchange/api-docs#82]
When I get my websocket token from the http api, then move over to the websocket to authenticate, I get the following message as a response : 

`{"error": {"code": 2, "message": "internal error"}, "result": null, "id": 0}`

**Comment by 82bladerunner** [comment]
This is what I'm sending to the websocket url: 
`var request = $"{{\"id\":0,\"method\":\"authorize\",\"params\":[\"{wsToken}\",\"public\"]}}";
            privateWsClient.Send(request);`

**Comment by john-whitebit** [comment]
Hello, 82bladerunner!
Please send your issue to our support via email support@whitebit.com or ask for help in live chat on https://whitebit.com !
